name: DarkAuctionsRevamped
main: com.ConquestTechMC.Main
version: 1.0
api-version: 1.18

depend:
  - PlaceholderAPI
  - MenuAPI
  - Vault

commands:
  auction:
    usage: /auction
    aliases:
      - auctions
      - darkauction
      - darkauctions
      - da